INPUT_DATA_DIR = "data/"
OUTPUT_DATA_DIR = "output/"
DEFAULT_INPUT_FILENAME = "ad_views.csv"
RECOMMENDATIONS_CSV_FILENAME = "ad_recommendations.csv"
RECOMMENDATIONS_JSON_FILENAME = "ad_recommendations.json"


BOREDOM_VS_VIEWS_PLOT_FILENAME = "boredom_vs_views.png"
BOREDOM_DISTRIBUTION_PLOT_FILENAME = "boredom_distribution.png"

SATURATION_VIEW_COUNT = 10

BOREDOM_THRESHOLD = 0.75

NUM_RECORDS_TO_GENERATE = 1000
NUM_USERS = 100
NUM_ADS = 20